#!/bin/bash
# Creates a public S3 bucket (if needed) and uploads the frontend.
# No CloudFront / CDN / OAC — bucket is publicly readable static website hosting.
set -euo pipefail

STACK_NAME="${STACK_NAME:-matchmaking-engine}"
REGION="${AWS_REGION:-$(aws configure get region || echo us-east-1)}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/frontend"

echo "Fetching stack outputs from $STACK_NAME ($REGION)..."

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --region "$REGION" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
        --output text
}

API_URL=$(get_output ApiEndpoint)
CLIENT_ID=$(get_output UserPoolClientId)

if [ -z "$API_URL" ] || [ -z "$CLIENT_ID" ]; then
    echo "Error: could not read ApiEndpoint / UserPoolClientId from stack $STACK_NAME."
    echo "Run 'sam deploy' first."
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET="${UI_BUCKET:-matchmaking-ui-${ACCOUNT_ID}-${REGION}}"

echo "Using bucket: s3://$BUCKET"

# ── Create the bucket if it doesn't already exist ────────────────────────────
if ! aws s3api head-bucket --bucket "$BUCKET" --region "$REGION" 2>/dev/null; then
    echo "Creating bucket..."
    if [ "$REGION" = "us-east-1" ]; then
        aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
    else
        aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
            --create-bucket-configuration LocationConstraint="$REGION"
    fi
else
    echo "Bucket already exists, reusing."
fi

# ── Make the bucket publicly readable ────────────────────────────────────────
echo "Configuring public access..."
aws s3api put-public-access-block --bucket "$BUCKET" --region "$REGION" \
    --public-access-block-configuration \
    "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

# Wait briefly for the public-access-block change to settle before the policy put.
sleep 2

cat > /tmp/matchmaking-ui-policy.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicRead",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::${BUCKET}/*"
    }
  ]
}
EOF
aws s3api put-bucket-policy --bucket "$BUCKET" --region "$REGION" \
    --policy file:///tmp/matchmaking-ui-policy.json
rm -f /tmp/matchmaking-ui-policy.json

# ── Enable static website hosting ────────────────────────────────────────────
echo "Enabling static website hosting..."
aws s3 website "s3://$BUCKET/" --index-document index.html --region "$REGION"

# ── Generate config.js from stack outputs ────────────────────────────────────
cat > "$FRONTEND_DIR/config.js" <<EOF
// Generated by scripts/deploy-ui.sh — do not edit by hand.
window.CONFIG = {
  apiUrl: "${API_URL}",
  clientId: "${CLIENT_ID}",
  region: "${REGION}"
};
EOF
echo "Generated $FRONTEND_DIR/config.js"

# ── Upload ───────────────────────────────────────────────────────────────────
echo "Uploading frontend to s3://$BUCKET ..."
aws s3 sync "$FRONTEND_DIR/" "s3://$BUCKET/" \
    --region "$REGION" \
    --delete \
    --exclude ".*"

URL="http://${BUCKET}.s3-website-${REGION}.amazonaws.com"
echo ""
echo "Deployed."
echo "URL: $URL"
echo ""
echo "Note: Cognito InitiateAuth is called directly from the browser, so no Cognito"
echo "callback URL configuration is required."
